[project]
name = "xgrammar"
description = "Efficient, Flexible and Portable Structured Generation"
authors = [
    { name = "MLC Team" }
]
version = "0.1.13"
readme = "README.md"
license = { text = "Apache 2.0" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
]
keywords = ["machine learning", "inference"]
requires-python = ">=3.8, <4"
dependencies = [
    "pybind11",
    "pydantic",
    "pytest",
    "sentencepiece",
    "tiktoken",
    "torch",
    "transformers",
]

[project.urls]
Homepage = "https://github.com/mlc-ai/xgrammar"

[build-system]
requires = [
    "scikit-build-core>=0.7.0",
    "pybind11>=2.11.0",
    "wheel",
    "cmake>=3.12",
    "ninja",
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.minimum-version = "3.12"
cmake.args = []  # Add any custom CMake arguments here
cmake.build-type = "Release"
cmake.verbose = true
wheel.packages = ["python/xgrammar"]  # Adjust to your package location
wheel.install-dir = "xgrammar"
sdist.include = [
    "3rdparty/**/*",
    "cmake/**/*",
    "CMakeLists.txt",
    "cpp/**/*.cc",
    "cpp/**/*.cpp",
    "cpp/**/*.h",
    "cpp/**/CMakeLists.txt",
    "docs/**/*",
    "include/**/*",
    "LICENSE",
    "python/xgrammar/**/*.py",
    "tests/**/*",
    "README.md",
    "NOTICE",
    "grammar_functor.cc", #??

]
sdist.exclude = [
    "**/.git",
    "**/.github",
    "**/__pycache__",
    "**/*.pyc",
    "build",
    "dist"
]

[tool.pytest.ini_options]
addopts = "-rA --durations=0 --ignore=3rdparty"

[tool.mypy]
strict = true

[tool.ruff]
exclude = ["3rdparty"]

[tool.ruff.lint]
ignore = [
  "E501",   # line too long, handled by black
  "PTH",
  "PGH",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D107",
  "D213",
  "D203",
  "D205",
  "D404",
  "D417",
  "D105",
  "FA",
  "ERA001",
  "SLF001",
]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["E741", "PLR2004", "INP001", "ANN201", "S101", "T201", "A", "FBT"]

[tool.ruff.lint.pylint]
max-args = 10

[tool.black]
exclude = "3rdparty/*"
line-length = 100

[tool.isort]
profile = "black"
src_paths = ["python"]