/*!
 *  Copyright (c) 2024 by Contributors
 * \file xgrammar/grammar_matcher.cc
 * \brief This source file implement the matcher class, especially the logic related to LLM tokens,
 * like accepting tokens, leveraging the token mask cache to generate the mask, etc. matcher_base.cc
 * implements the basic matching algorithm from strings to grammar.
 */

#include <dlpack/dlpack.h>
#include <xgrammar/matcher.h>

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <optional>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

#include "compiled_grammar_impl.h"
#include "earley_parser.h"
#include "grammar_impl.h"
#include "support/dynamic_bitset.h"
#include "support/encoding.h"
#include "support/int_set.h"
#include "support/logging.h"
#include "support/thread_pool.h"
#include "testing.h"

namespace xgrammar {

/******************* Tool functions for token mask *******************/
using GrammarExprType = Grammar::Impl::GrammarExprType;

int32_t GetBitmaskSize(int vocab_size) { return DynamicBitset::GetBufferSize(vocab_size); }

DLDataType GetBitmaskDLType() { return DLDataType{kDLInt, 32, 1}; }

namespace details {

using Clock = std::chrono::steady_clock;
using TimePoint = Clock::time_point;

void ClearTokenBitmaskRow(int32_t* bitmask_data, int32_t bitmask_size, int32_t position) {
  std::fill_n(bitmask_data + position * bitmask_size, bitmask_size, 0);
}

bool TraverseDraftTreeRecursive(
    int32_t current_position,
    int32_t parent_position,
    const int64_t* retrieve_next_token,
    const int64_t* retrieve_next_sibling,
    const int64_t* draft_tokens,
    GrammarMatcher& matcher,
    DLTensor* token_bitmask,
    double time_threshold,
    const TimePoint& start_time
) {
  int32_t* bitmask_data = reinterpret_cast<int32_t*>(token_bitmask->data);
  int32_t bitmask_size = static_cast<int32_t>(token_bitmask->shape[1]);

  bool accepted;
  if (current_position == 0) {
    // The first token generated by the target model is always accepted.
    accepted = true;
  } else {
    XGRAMMAR_CHECK(parent_position >= 0)
        << "Non-root draft tree nodes must have a valid parent position";
    int64_t current_token_id = draft_tokens[current_position];
    if (current_token_id < 0 || current_token_id >= static_cast<int64_t>(bitmask_size) * 32) {
      accepted = false;
    } else {
      int32_t* parent_bitmask = bitmask_data + parent_position * bitmask_size;
      // 32 boolean bitmask values are packed into 32-bit integers.
      uint32_t token_mask = uint32_t{1} << static_cast<uint32_t>(current_token_id % 32);
      accepted = (static_cast<uint32_t>(parent_bitmask[current_token_id / 32]) & token_mask) != 0;
    }

    // Check timeout for non-root nodes so the root token mask is still computed.
    if (accepted && time_threshold > 0) {
      auto elapsed = std::chrono::duration<double>(Clock::now() - start_time).count();
      if (elapsed > time_threshold) {
        return false;
      }
    }
  }

  if (accepted) {
    bool token_accepted = true;
    if (current_position != 0) {
      token_accepted = matcher.AcceptToken(static_cast<int32_t>(draft_tokens[current_position]));
    }

    if (token_accepted) {
      if (!matcher.IsTerminated()) {
        matcher.FillNextTokenBitmask(token_bitmask, current_position);

        if (retrieve_next_token[current_position] != -1) {
          bool success = TraverseDraftTreeRecursive(
              retrieve_next_token[current_position],
              current_position,
              retrieve_next_token,
              retrieve_next_sibling,
              draft_tokens,
              matcher,
              token_bitmask,
              time_threshold,
              start_time
          );
          if (!success) {
            if (current_position != 0) {
              matcher.Rollback(1);
            }
            return false;
          }
        }
      } else {
        ClearTokenBitmaskRow(bitmask_data, bitmask_size, current_position);
      }

      if (current_position != 0) {
        matcher.Rollback(1);
      }
    } else {
      ClearTokenBitmaskRow(bitmask_data, bitmask_size, current_position);
    }
  } else {
    ClearTokenBitmaskRow(bitmask_data, bitmask_size, current_position);
  }

  if (retrieve_next_sibling[current_position] != -1) {
    bool success = TraverseDraftTreeRecursive(
        retrieve_next_sibling[current_position],
        parent_position,
        retrieve_next_token,
        retrieve_next_sibling,
        draft_tokens,
        matcher,
        token_bitmask,
        time_threshold,
        start_time
    );
    if (!success) {
      return false;
    }
  }

  return true;
}

}  // namespace details

int32_t* CheckAndGetBitmaskPtr(const DLTensor& token_bitmask, int vocab_size, int index) {
  XGRAMMAR_CHECK(token_bitmask.dtype.code == kDLInt && token_bitmask.dtype.bits == 32)
      << "The provied bitmask's dtype is not valid: should be int32";

  int32_t buffer_size = GetBitmaskSize(vocab_size);
  if (token_bitmask.ndim == 1) {
    XGRAMMAR_CHECK(token_bitmask.shape[0] == buffer_size)
        << "The provided bitmask's shape is not valid: should be (" << buffer_size << ", )";
    XGRAMMAR_CHECK(index == 0) << "The index should be 0 when the bitmask is 1D";
  } else {
    XGRAMMAR_CHECK(token_bitmask.ndim == 2)
        << "The provided bitmask's shape is not valid: should be (batch_size, " << buffer_size
        << ")";
    XGRAMMAR_CHECK(token_bitmask.shape[1] == buffer_size)
        << "The provided bitmask's shape is not valid: should be (batch_size, " << buffer_size
        << ")";
    XGRAMMAR_CHECK(index >= 0 && index < token_bitmask.shape[0])
        << "The provided index is out of bounds";
  }

  XGRAMMAR_CHECK(
      token_bitmask.device.device_type == kDLCPU ||
      token_bitmask.device.device_type == kDLCUDAHost ||
      token_bitmask.device.device_type == kDLROCMHost
  ) << "The provided bitmask's device is not valid: should be CPU";

  return reinterpret_cast<int32_t*>(token_bitmask.data) + index * buffer_size;
}

void _DebugGetMaskedTokensFromBitmask(
    std::vector<int>* rejected_tokens, const DLTensor& token_bitmask, int vocab_size, int index
) {
  int32_t* data_ptr = CheckAndGetBitmaskPtr(token_bitmask, vocab_size, index);
  DynamicBitset bitset(vocab_size, reinterpret_cast<uint32_t*>(data_ptr));
  rejected_tokens->clear();
  for (int i = bitset.FindFirstZero(); i != -1; i = bitset.FindNextZero(i)) {
    rejected_tokens->push_back(i);
  }
}

std::pair<bool, int> _IsSingleTokenBitmask(const DLTensor& bitmask, int vocab_size, int index) {
  int32_t* data_ptr = CheckAndGetBitmaskPtr(bitmask, vocab_size, index);
  DynamicBitset bitset(vocab_size, reinterpret_cast<uint32_t*>(data_ptr));
  if (bitset.Count() == 1) {
    return std::make_pair(true, bitset.FindFirstOne());
  } else {
    return std::make_pair(false, -1);
  }
}

void ApplyMask32Bits(
    DLTensor* logits,
    const DLTensor& bitmask,
    int vocab_size,
    std::optional<std::vector<int>> indices
) {
  XGRAMMAR_CHECK(logits->dtype.code == kDLFloat && logits->dtype.bits == 32)
      << "The provided logits's dtype is not valid: should be float32";
  std::pair<int, int> logits_shape =
      logits->ndim == 2
          ? std::make_pair(static_cast<int>(logits->shape[0]), static_cast<int>(logits->shape[1]))
          : std::make_pair(1, static_cast<int>(logits->shape[0]));
  int logits_stride0 = logits->strides[0];
  int bitmask_stride0 = bitmask.strides[0];
  if (indices.has_value()) {
    for (auto idx : indices.value()) {
      uint32_t* data_ptr = reinterpret_cast<uint32_t*>(bitmask.data) + idx * bitmask_stride0;
      DynamicBitset bitset(vocab_size, data_ptr);
      auto logits_ptr = reinterpret_cast<float*>(logits->data) + idx * logits_stride0;
      for (int i = bitset.FindFirstZero(); i != -1; i = bitset.FindNextZero(i)) {
        logits_ptr[i] = -std::numeric_limits<float>::infinity();
      }
    }
  } else {
    for (int idx = 0; idx < logits_shape.first; ++idx) {
      uint32_t* data_ptr = reinterpret_cast<uint32_t*>(bitmask.data) + idx * bitmask_stride0;
      DynamicBitset bitset(vocab_size, data_ptr);
      auto logits_ptr = reinterpret_cast<float*>(logits->data) + idx * logits_stride0;
      for (int i = bitset.FindFirstZero(); i != -1; i = bitset.FindNextZero(i)) {
        logits_ptr[i] = -std::numeric_limits<float>::infinity();
      }
    }
  }
}

void ApplyMask16Bits(
    DLTensor* logits,
    const DLTensor& bitmask,
    int vocab_size,
    std::optional<std::vector<int>> indices
) {
  XGRAMMAR_CHECK(logits->dtype.bits == 16)
      << "The provided logits's dtype is not valid: should be bfloat16 or float16";
  uint16_t kMinusInfinity;
  const uint16_t kMinusInfinityBf16 = 0xff80;
  const uint16_t kMinusInfinityFp16 = 0xfc00;
  switch (logits->dtype.code) {
    case kDLBfloat:
      kMinusInfinity = kMinusInfinityBf16;
      break;
    case kDLFloat:
      kMinusInfinity = kMinusInfinityFp16;
      break;
    default:
      XGRAMMAR_LOG(FATAL
      ) << "The provided logits's dtype is not valid: should be bfloat16 or float16";
  }
  std::pair<int, int> logits_shape =
      logits->ndim == 2
          ? std::make_pair(static_cast<int>(logits->shape[0]), static_cast<int>(logits->shape[1]))
          : std::make_pair(1, static_cast<int>(logits->shape[0]));
  int logits_stride0 = logits->strides[0];
  int bitmask_stride0 = bitmask.strides[0];
  if (indices.has_value()) {
    for (auto idx : indices.value()) {
      uint32_t* data_ptr = reinterpret_cast<uint32_t*>(bitmask.data) + idx * bitmask_stride0;
      DynamicBitset bitset(vocab_size, data_ptr);
      auto logits_ptr = reinterpret_cast<uint16_t*>(logits->data) + idx * logits_stride0;
      for (int i = bitset.FindFirstZero(); i != -1; i = bitset.FindNextZero(i)) {
        logits_ptr[i] = kMinusInfinity;
      }
    }
  } else {
    for (int idx = 0; idx < logits_shape.first; ++idx) {
      uint32_t* data_ptr = reinterpret_cast<uint32_t*>(bitmask.data) + idx * bitmask_stride0;
      DynamicBitset bitset(vocab_size, data_ptr);
      auto logits_ptr = reinterpret_cast<uint16_t*>(logits->data) + idx * logits_stride0;
      for (int i = bitset.FindFirstZero(); i != -1; i = bitset.FindNextZero(i)) {
        logits_ptr[i] = kMinusInfinity;
      }
    }
  }
}

void ApplyTokenBitmaskInplaceCPU(
    DLTensor* logits,
    const DLTensor& bitmask,
    int vocab_size,
    std::optional<std::vector<int>> indices
) {
  // Check device and dim
  XGRAMMAR_CHECK(
      logits->device.device_type == kDLCPU || logits->device.device_type == kDLCUDAHost ||
      logits->device.device_type == kDLROCMHost
  ) << "The provided logits's device is not valid: should be CPU";
  XGRAMMAR_CHECK(
      bitmask.device.device_type == kDLCPU || bitmask.device.device_type == kDLCUDAHost ||
      bitmask.device.device_type == kDLROCMHost
  ) << "The provided bitmask's device is not valid: should be CPU";
  XGRAMMAR_CHECK(logits->ndim == 2 || logits->ndim == 1)
      << "The provided logits's shape is not valid: should be 2D or 1D";
  XGRAMMAR_CHECK(bitmask.ndim == 2 || bitmask.ndim == 1)
      << "The provided bitmask's shape is not valid: should be 2D or 1D";

  // Check type
  XGRAMMAR_CHECK(logits->dtype.lanes == 1)
      << "The provided logits's dtype is not valid: lanes should be 1";
  XGRAMMAR_CHECK(
      bitmask.dtype.code == kDLInt && bitmask.dtype.bits == 32 && bitmask.dtype.lanes == 1
  ) << "The provided bitmask's dtype is not valid: should be int32";

  // Check shape
  std::pair<int, int> logits_shape =
      logits->ndim == 2
          ? std::make_pair(static_cast<int>(logits->shape[0]), static_cast<int>(logits->shape[1]))
          : std::make_pair(1, static_cast<int>(logits->shape[0]));
  std::pair<int, int> bitmask_shape =
      bitmask.ndim == 2
          ? std::make_pair(static_cast<int>(bitmask.shape[0]), static_cast<int>(bitmask.shape[1]))
          : std::make_pair(1, static_cast<int>(bitmask.shape[0]));

  XGRAMMAR_CHECK(
      vocab_size <= bitmask_shape.second * DynamicBitset::BITS_PER_BLOCK &&
      vocab_size <= logits_shape.second
  );

  if (!indices.has_value()) {
    XGRAMMAR_CHECK(logits_shape.first == bitmask_shape.first)
        << "When indices is not provided, the logits's batch size should be equal to the "
           "bitmask's batch size, but got "
        << logits_shape.first << " vs " << bitmask_shape.first;
  }

  // Apply mask
  if (logits->dtype.bits == 32) {
    ApplyMask32Bits(logits, bitmask, vocab_size, indices);
  } else if (logits->dtype.bits == 16) {
    ApplyMask16Bits(logits, bitmask, vocab_size, indices);
  } else {
    XGRAMMAR_LOG(FATAL
    ) << "The provided logits's dtype is not valid: should be float32 or float16/bfloat16";
  }
}

/******************* Grammar Matcher with Adaptive Token Mask *******************/

/*
 * Note on the matching algorithm (this is the old description for the matching algorithm, please
 * refer to https://arxiv.org/pdf/2411.15100 for the latest description)
 *
 * Given a context-free grammar, we match the characters in a string one by one.
 *
 * We adopt a non-deterministic pushdown automata (NPDA) in matching. To be specific, we maintain
 * several stacks, each of which represents a possible path in the NPDA, and update the stacks
 * during matching.
 *
 * ## Stack Structure (see grammar_matcher_state.h)
 * The element of every stack is a StackElement object, referring a position in the grammar. If a
 * StackElement points to a RuleRef element (referring to another rule), the next element of the
 * stack will be a position in this rule. If a StackElement is a CharacterClass element, it will be
 * the last in the stack, meaning *the next* character to match.
 *
 * ## Matching Process (see grammar_matcher_base.h)
 * When accepting a new character and it is accepted by a stack, the last element of the stack will
 * be advanced to the next position in the grammar. If it gets to the end of the rule, several
 * elements at the end may be popped out, and the last element of the stack will be advanced.
 *
 * One stack may split since there may be multiple possible next positions. In this case, similar
 * stacks with different top elements will be added. When one stack cannot accept the new character,
 * it will be removed from the stacks.
 *
 * ## Storage of Stacks (see grammar_matcher_state.h)
 * Note these stacks form a tree structure as when splitting, the new stacks share the same prefix.
 * We store all StackElements as a tree, where every path from tree root to a node represents a
 * stack. To represent stack tops, we attach additional pointers pointing the stack top nodes.
 * Also, We maintain a history of the stack top pointers, so we can rollback to the previous state.
 *
 * All tree nodes are maintained by a buffer, and utilize reference counting to recycle. If a node
 * is neither pointed by a stack top pointer, not pointed by some child nodes, it will be freed.
 *
 * ## Example
 * ### Grammar
 * root ::= [a] R
 * R ::= [b] S [c] | [b] [c] T
 * S ::= "" | [c] [d]
 * T ::= [e]
 *
 * ### The previous step
 * Previous accepted string: ab
 * Previous stack tree:
 * A------
 * |  \   \
 * B   D<  E<
 * |
 * C<
 *
 * A: (rule root, choice 0, element 1)
 * B: (rule R, choice 0, element 1)
 * C: (rule S, choice 1, element 0)
 * D: (rule R, choice 0, element 2)
 * E: (rule R, choice 1, element 1)
 * < means the stack top pointers in the previous step.
 * The stacks in the previous step is: (A, B, C), (A, D), (A, E)
 *
 * ### The current step
 * Current accepted string: abc
 * Current stack tree:
 * A-----------------      G<<
 * |     \     \     \
 * B---   D<    E<    H
 * |   \              |
 * C<   F<<           I<<
 *
 * F: (rule S, choice 1, element 1)
 * G: (rule root, choice 0, element 2) (means the matching process has finished, and will be deleted
 * when the next char comes)
 * H: (rule R, choice 1, element 2)
 * I: (rule T, choice 0, element 0)
 * << means the stack top pointers in the current step.
 * The stacks in the current step is: (A, B, F), (A, H, I), (G,)
 *
 * ## Preprocess (see grammar_matcher_preproc.h)
 * We will store all information about tokens that needed in matching in a CompiledGrammar
 * object. Tokens are sorted by codepoint, allowing us to reuse the repeated prefixes between
 * different tokens.
 *
 * For a given position in a rule, if we only consider this rule and its sub-rules during matching,
 * without considering its parent rules (in actual matching, we also need to consider its parent
 * rules), we can already determine that some tokens are acceptable while others are definitely
 * rejected. Therefore, for a position in a rule, we can divide the token set into three categories:
 * - accepted_indices: If a token is accepted by this rule
 * - rejected_indices: If a token is rejected by this rule
 * - uncertain_indices: Whether it can be accepted depends on the information from the parent
 * level during actual matching. To be specific, If this token has a prefix that has not been
 * rejected and has reached the end of this rule, then it is possible for it to be further accepted
 * by the parent rule.
 *
 * During actual matching, we will directly accept or reject the tokens in accepted_indices and
 * rejected_indices, and only consider the tokens in uncertain_indices. That speeds up the matching
 * process.
 */

/* \brief The concrete implementation of GrammarMatcherNode. */
class GrammarMatcher::Impl : public EarleyParser {
 public:
  Impl(
      const CompiledGrammar& compiled_grammar,
      std::optional<std::vector<int>> override_stop_tokens = std::nullopt,
      bool terminate_without_stop_token = false,
      // max_rollback_tokens_ is deprecated and not used.
      int max_rollback_tokens = -1
  )
      : EarleyParser(compiled_grammar->grammar),
        compiled_grammar_(compiled_grammar),
        tokenizer_info_(compiled_grammar->tokenizer_info),
        stop_token_ids_(override_stop_tokens.value_or(tokenizer_info_.GetStopTokenIds())),
        terminate_without_stop_token_(terminate_without_stop_token),
        tmp_accepted_bitset_(tokenizer_info_.GetVocabSize()) {
    XGRAMMAR_CHECK(!override_stop_tokens.has_value() || !override_stop_tokens->empty())
        << "The override_stop_tokens should not be empty";
    if (has_budget_rules_) {
      for (int32_t rule_id = 0; rule_id < grammar_->NumRules(); ++rule_id) {
        const auto& rule = grammar_->GetRule(rule_id);
        if (rule.max_tokens < 0) {
          continue;
        }
        const auto* suffix_stop_info = grammar_->GetSuffixStopInfo(rule_id);
        if (suffix_stop_info != nullptr && suffix_stop_info->body_rule_id >= 0) {
          has_budget_marker_rules_ = true;
          break;
        }
      }
    }
  }

  bool AcceptToken(int32_t token_id, bool debug_print = false);

  bool AcceptString(const std::string& input_str, bool debug_print = false);

  bool FillNextTokenBitmask(DLTensor* next_token_bitmask, int index, bool debug_print = false);

  std::string FindJumpForwardString();

  void Rollback(int num_tokens);

  bool IsTerminated() const;

  void Reset() {
    token_length_history.clear();
    current_token_index_ = -1;
    budget_enforce_pending_ = false;
    budget_force_close_pending_ = false;
    budget_exceeded_warned_ = false;
    budget_body_match_cache_.clear();
    accepted_bytes_.clear();
    row_byte_end_.assign(1, 0);
    EarleyParser::Reset();
  }

  std::vector<std::pair<std::string, std::string>> GetCaptures(bool deduplicate) const;

  int GetMaxRollbackTokens() const { return -1; }

  const std::vector<int>& GetStopTokenIds() const { return stop_token_ids_; }

  std::string _DebugPrintInternalState() const { return PrintStates(); }

 private:
  using StoreType = AdaptiveTokenMask::StoreType;

  /*!
   * \brief If is_uncertain_saved is true, find the next token in uncertain_indices. Otherwise,
   * find the next token that is set to true in uncertain_tokens_bitset.
   * \param iterator_uncertain The helper iterator to iterate over uncertain_indices or
   * uncertain_tokens_bitset.
   * \returns The index of the next token, or -1 if no more token.
   */
  int GetNextUncertainToken(
      bool is_uncertain_saved,
      int* iterator_uncertain,
      const std::vector<int>& uncertain_indices,
      const std::vector<bool>& uncertain_tokens_bitset
  );

  /*! \brief Set the acceptable next token in next_token_bitmask. */
  void SetTokenBitmask(
      int32_t* bitmask_data_ptr,
      const DynamicBitset& accepted_bitset,
      const std::vector<int32_t>& rejected_indices,
      bool can_reach_end,
      bool allow_special_token = false
  );

  /*!
   * \brief Accept the stop token and terminates the matcher.
   * \returns Whether the stop token can be accepted.
   */
  bool AcceptStopToken();

  bool IsStopTokenAccepted() const;

  /*! \brief Check if the token bitmask is all-true. */
  bool IsTokenBitmaskAllTrue(int32_t* bitmask_data_ptr);

  std::string PrintBitmask(int32_t* bitmask_data_ptr, const TokenizerInfo& tokenizer_info);

  /*! \brief Restores skip_expired_states_ to false when the accept call returns. */
  class SkipExpiredGuard {
   public:
    explicit SkipExpiredGuard(Impl* impl, bool enable) : impl_(impl) {
      impl_->skip_expired_states_ = enable;
    }
    ~SkipExpiredGuard() { impl_->skip_expired_states_ = false; }
    SkipExpiredGuard(const SkipExpiredGuard&) = delete;
    SkipExpiredGuard& operator=(const SkipExpiredGuard&) = delete;

   private:
    Impl* impl_;
  };

  /*!
   * \brief RAII guard that enables capture-event recording in the Earley parser for its
   * lifetime. Used in the definitive accept paths (AcceptToken / AcceptString) only, so that
   * speculative advances (mask computation, jump-forward search) never record capture events.
   */
  class CaptureRecordingGuard {
   public:
    explicit CaptureRecordingGuard(Impl* impl) : impl_(impl) {
      if (impl_->capture_tracking_) {
        impl_->capture_recording_ = true;
      }
    }
    ~CaptureRecordingGuard() { impl_->capture_recording_ = false; }
    CaptureRecordingGuard(const CaptureRecordingGuard&) = delete;
    CaptureRecordingGuard& operator=(const CaptureRecordingGuard&) = delete;

   private:
    Impl* impl_;
  };

  /*! \brief Fill the bitmask from the current states, optionally excluding the states whose
   * budget deadline has passed. */
  void FillBitmaskForStates(
      int32_t* bitmask_data_ptr, int index, bool skip_expired, bool debug_print
  );

  /*! \brief Whether byte offsets are needed for captures or budgeted suffix/stop rules. */
  bool ShouldTrackAcceptedBytes() const {
    return IsCaptureTrackingEnabled() || has_budget_marker_rules_;
  }

  /*! \brief Whether the bytes consumed by this expired suffix/stop occurrence form a complete
   * match of its body, so max_tokens may end it without consuming the marker. */
  bool CanForceCompleteWithoutMarker(const ParserState& state);

  /*! \brief Commit the current budget boundary: discard expired states and complete eligible
   * suffix/stop occurrences without their marker. Returns whether a derivation remains viable. */
  bool ApplyBudgetEnforcement(bool debug_print = false);

  /*! \brief Consume the pending budget decision and warn once when a token budget was
   * exceeded. */
  bool FinishAccept(bool consumed_past_deadline) {
    budget_enforce_pending_ = false;
    budget_force_close_pending_ = false;
    if (consumed_past_deadline && !budget_exceeded_warned_) {
      budget_exceeded_warned_ = true;
      XGRAMMAR_LOG(WARNING
      ) << "The token budget (max_tokens) of a rule was exceeded: the rule could not end at "
           "the position where its budget ran out, so the budget is relaxed until the rule "
           "can end. This warning is reported once per matcher.";
    }
    return true;
  }

  bool BitmaskHasAnyToken(int32_t* bitmask_data_ptr) const {
    auto bitset = DynamicBitset(
        tokenizer_info_.GetVocabSize(), reinterpret_cast<uint32_t*>(bitmask_data_ptr)
    );
    return bitset.Any();
  }

  /*! \brief Record that num_rows new input positions were created, each consuming one byte of
   * bytes in order. Used for the byte-by-byte advance paths. */
  void AppendPerByteRows(const std::string& bytes) {
    for (char c : bytes) {
      accepted_bytes_.push_back(static_cast<uint8_t>(c));
      row_byte_end_.push_back(static_cast<int64_t>(accepted_bytes_.size()));
    }
  }

  /*! \brief Record that one new input position was created, consuming all bytes of the token.
   * Used for the atomic token advance path. */
  void AppendAtomicRow(const std::string& bytes) {
    accepted_bytes_.insert(accepted_bytes_.end(), bytes.begin(), bytes.end());
    row_byte_end_.push_back(static_cast<int64_t>(accepted_bytes_.size()));
  }

  CompiledGrammar compiled_grammar_;
  TokenizerInfo tokenizer_info_;
  std::vector<int> stop_token_ids_;
  bool terminate_without_stop_token_;
  std::deque<int> token_length_history;

  /*! \brief Set by the last mask computation when an exhausted budget could be enforced: the
   * next accept commits the same state transition used to compute that mask. */
  bool budget_enforce_pending_ = false;
  /*! \brief Whether the pending decision includes a suffix/stop completion without its marker. */
  bool budget_force_close_pending_ = false;
  /*! \brief Whether the one-time budget-exceeded warning has been reported. */
  bool budget_exceeded_warned_ = false;
  /*! \brief Whether byte history is needed to recognize a budgeted suffix/stop body boundary. */
  bool has_budget_marker_rules_ = false;

  struct BudgetBodyMatchProgress {
    int64_t begin_byte;
    int64_t end_byte;
    std::unordered_set<int> states;
  };
  /*! \brief Incremental body-FSM progress keyed by (rule id, occurrence start row). */
  std::unordered_map<int64_t, BudgetBodyMatchProgress> budget_body_match_cache_;

  /*! \brief The bytes accepted so far. Maintained for captures and budgeted marker rules. */
  std::vector<uint8_t> accepted_bytes_;
  /*! \brief row_byte_end_[i] is the number of accepted bytes after input position i. Aligned
   * with the parser's state history whenever accepted_bytes_ is maintained. */
  std::vector<int64_t> row_byte_end_{0};

  // Temporary data for FillNextTokenBitmask. They are stored here to avoid repeated allocation.
  DynamicBitset tmp_accepted_bitset_;
  std::vector<int32_t> tmp_rejected_indices_;
  std::vector<int32_t> tmp_rejected_indices_delta_;
};

class BatchGrammarMatcher::Impl {
 public:
  Impl(std::variant<std::string, int32_t> max_threads) {
    if (std::holds_alternative<int32_t>(max_threads)) {
      int32_t num_threads = std::get<int32_t>(max_threads);
      XGRAMMAR_CHECK(num_threads >= 1)
          << "The num_threads should be at least 1, but got " << num_threads;
      if (num_threads > 1) {
        if (num_threads > static_cast<int32_t>(std::thread::hardware_concurrency())) {
          XGRAMMAR_LOG(WARNING) << "The num_threads " << num_threads << " is larger than the "
                                << "number of hardware threads. Using "
                                << static_cast<int32_t>(std::thread::hardware_concurrency())
                                << " instead.";
        }
        max_threads_ =
            std::min(num_threads, static_cast<int32_t>(std::thread::hardware_concurrency()));
      }
    } else {
      std::string str = std::get<std::string>(max_threads);
      XGRAMMAR_CHECK(str == "auto");
      max_threads_ = std::thread::hardware_concurrency() / 2;
    }
  }

  void BatchFillNextTokenBitmask(
      std::vector<GrammarMatcher>* matchers,
      DLTensor* next_token_bitmask,
      const std::optional<std::vector<int32_t>>& indices,
      bool debug_print
  );

  static std::vector<uint8_t> BatchAcceptToken(
      std::vector<GrammarMatcher>* matchers, const std::vector<int32_t>& token_ids, bool debug_print
  );

  static std::vector<uint8_t> BatchAcceptString(
      std::vector<GrammarMatcher>* matchers,
      const std::vector<std::string>& input_strs,
      bool debug_print
  );

  static void BatchRollback(
      std::vector<GrammarMatcher>* matchers, const std::vector<int>& num_tokens
  );

 private:
  std::optional<ThreadPool> thread_pool_ = std::nullopt;
  int32_t max_threads_ = 1;
};

bool GrammarMatcher::Impl::AcceptStopToken() {
  if (terminate_without_stop_token_) {
    return false;
  }
  if (!IsCompleted()) {
    return false;
  }
  XGRAMMAR_DCHECK(!stop_token_is_accepted_);
  token_length_history.push_back(0);
  stop_token_is_accepted_ = true;
  return true;
}

bool GrammarMatcher::Impl::IsTerminated() const {
  if (terminate_without_stop_token_) {
    return IsCompleted();
  }
  return IsStopTokenAccepted();
}

bool GrammarMatcher::Impl::IsStopTokenAccepted() const { return stop_token_is_accepted_; }

bool GrammarMatcher::Impl::CanForceCompleteWithoutMarker(const ParserState& state) {
  if (!IsExpiredState(state) || state.rule_id < 0) {
    return false;
  }
  const auto& rule = grammar_->GetRule(state.rule_id);
  if (rule.max_tokens < 0) {
    return false;
  }
  const auto* suffix_stop_info = grammar_->GetSuffixStopInfo(state.rule_id);
  if (suffix_stop_info == nullptr || suffix_stop_info->body_rule_id < 0) {
    return false;
  }
  XGRAMMAR_DCHECK(ShouldTrackAcceptedBytes());
  XGRAMMAR_DCHECK(row_byte_end_.size() == static_cast<size_t>(scanable_state_history_.size()));
  int32_t start_row =
      state.rule_start_pos == ParserState::kNoPrevInputPos ? 0 : state.rule_start_pos;
  XGRAMMAR_DCHECK(start_row >= 0 && start_row < static_cast<int32_t>(row_byte_end_.size()));
  int64_t begin = row_byte_end_[start_row];
  int64_t end = row_byte_end_.back();

  XGRAMMAR_DCHECK(grammar_->per_rule_fsms[suffix_stop_info->body_rule_id].has_value());
  const auto& body_fsm = grammar_->per_rule_fsms[suffix_stop_info->body_rule_id]->GetFsm();
  XGRAMMAR_DCHECK(body_fsm.IsLeaf()) << "A suffix/stop body helper must compile to a leaf FSM";

  int64_t occurrence =
      (static_cast<int64_t>(state.rule_id) << 32) | static_cast<uint32_t>(state.rule_start_pos);
  auto [it, inserted] = budget_body_match_cache_.try_emplace(
      occurrence, BudgetBodyMatchProgress{begin, begin, {body_fsm.GetStart()}}
  );
  auto& progress = it->second;
  if (inserted) {
    body_fsm.GetFsm().GetEpsilonClosure(&progress.states);
  } else if (progress.begin_byte != begin || progress.end_byte > end) {
    // This is only expected after restoring external matcher state. Rollback and reset clear the
    // cache eagerly, but reinitialize defensively if a caller supplies an equivalent history.
    progress = BudgetBodyMatchProgress{begin, begin, {body_fsm.GetStart()}};
    body_fsm.GetFsm().GetEpsilonClosure(&progress.states);
  }

  std::unordered_set<int> next_states;
  for (int64_t offset = progress.end_byte; offset < end && !progress.states.empty(); ++offset) {
    body_fsm.GetFsm().Advance(
        progress.states, accepted_bytes_[offset], &next_states, FSMEdge::EdgeType::kCharRange, true
    );
    progress.states = next_states;
  }
  progress.end_byte = end;
  return std::any_of(progress.states.begin(), progress.states.end(), [&](int state_id) {
    return body_fsm.IsEndState(state_id);
  });
}

bool GrammarMatcher::Impl::ApplyBudgetEnforcement(bool debug_print) {
  XGRAMMAR_DCHECK(tmp_process_state_queue_.empty());
  const auto latest_row = scanable_state_history_[scanable_state_history_.size() - 1];
  std::vector<ParserState> latest_states(latest_row.begin(), latest_row.end());
  std::vector<ParserState> force_completed_states;
  std::unordered_set<int64_t> force_completed_occurrences;

  tmp_states_visited_in_queue_.Clear();
  tmp_states_to_be_added_.clear();
  tmp_completed_lazy_occurrences_.clear();
  tmp_accept_stop_token_ = IsCompleted();

  for (const auto& state : latest_states) {
    if (!IsExpiredState(state)) {
      EnqueueWithoutProcessing(state);
      continue;
    }
    if (!CanForceCompleteWithoutMarker(state)) {
      continue;
    }
    int64_t occurrence =
        (static_cast<int64_t>(state.rule_id) << 32) | static_cast<uint32_t>(state.rule_start_pos);
    if (force_completed_occurrences.insert(occurrence).second) {
      force_completed_states.push_back(state);
    }
  }

  for (const auto& state : force_completed_states) {
    Complete(state, debug_print, /*marker_present=*/false);
  }
  while (!tmp_process_state_queue_.empty()) {
    const auto state = std::move(tmp_process_state_queue_.front());
    tmp_process_state_queue_.pop();
    auto [scanable, completable] = Predict(state, debug_print);
    if (completable) {
      Complete(state, debug_print);
    }
    if (scanable) {
      tmp_states_to_be_added_.push_back(state);
    }
  }
  if (!tmp_completed_lazy_occurrences_.empty()) {
    RemoveCommittedLazyStates();
  }

  bool any_expired = false;
  bool any_alive = false;
  for (const auto& state : tmp_states_to_be_added_) {
    if (IsExpiredState(state)) {
      any_expired = true;
    } else {
      any_alive = true;
    }
  }
  if (any_expired && (any_alive || tmp_accept_stop_token_)) {
    // Completing a budgeted suffix/stop rule can expose an already-expired parent alternative.
    // Apply the same preference as the ordinary max_tokens path: once another derivation can
    // continue or finish at this boundary, expired derivations may not consume another token.
    tmp_states_to_be_added_.erase(
        std::remove_if(
            tmp_states_to_be_added_.begin(),
            tmp_states_to_be_added_.end(),
            [&](const ParserState& state) { return IsExpiredState(state); }
        ),
        tmp_states_to_be_added_.end()
    );
  }

  bool viable = tmp_accept_stop_token_ || !tmp_states_to_be_added_.empty();
  if (!viable) {
    return false;
  }
  scanable_state_history_.PopBack(1);
  scanable_state_history_.PushBack(tmp_states_to_be_added_);
  is_completed_.back() = tmp_accept_stop_token_;
  return true;
}

// TODO(yixin): Polish verbose logging
bool GrammarMatcher::Impl::AcceptToken(int32_t token_id, bool debug_print) {
  if (IsStopTokenAccepted()) {
    XGRAMMAR_LOG(WARNING) << "The matcher has terminated after accepting the stop token, but is "
                          << "trying to accept new token with id " << token_id << ".";
    return false;
  }

  if (token_id < 0 || token_id >= tokenizer_info_.GetVocabSize()) {
    XGRAMMAR_LOG(WARNING) << "The token id " << token_id << " is out of range [0, "
                          << tokenizer_info_.GetVocabSize() << "). Rejecting the token.";
    return false;
  }

  bool is_stop_token =
      std::find(stop_token_ids_.begin(), stop_token_ids_.end(), token_id) != stop_token_ids_.end();
  const auto& special_token_ids = tokenizer_info_.GetSpecialTokenIds();
  if (!is_stop_token && std::find(special_token_ids.begin(), special_token_ids.end(), token_id) !=
                            special_token_ids.end()) {
    XGRAMMAR_LOG(WARNING) << "GrammarMatcher cannot accept special token id " << token_id << ": "
                          << tokenizer_info_.GetDecodedVocab()[token_id]
                          << ". Rejecting the token.";
    return false;
  }

  current_token_index_ = static_cast<int32_t>(token_length_history.size());
  bool enforce_budget = budget_enforce_pending_;
  bool force_budget_close = budget_force_close_pending_;
  if (force_budget_close) {
    // Validate on a copy first: a rejected token must not commit the budget-close transition.
    Impl trial(*this);
    trial.capture_recording_ = false;
    bool applied = trial.ApplyBudgetEnforcement();
    XGRAMMAR_DCHECK(applied);
    if (!applied) {
      return false;
    }
    trial.budget_enforce_pending_ = false;
    trial.budget_force_close_pending_ = false;
    if (!trial.AcceptToken(token_id, false)) {
      return false;
    }
  }

  // Capture events are only recorded on the definitive accept path.
  CaptureRecordingGuard capture_guard(this);
  if (force_budget_close) {
    bool applied = ApplyBudgetEnforcement(debug_print);
    XGRAMMAR_DCHECK(applied);
    if (!applied) {
      return false;
    }
    budget_enforce_pending_ = false;
    budget_force_close_pending_ = false;
  }
  SkipExpiredGuard skip_expired_guard(this, enforce_budget && !force_budget_close);

  // The token extends a derivation past its budget iff expired states are allowed to scan
  // (no enforcement) while some exist.
  bool consumed_past_deadline = false;
  if (has_budget_rules_ && !enforce_budget) {
    const auto& row = scanable_state_history_[scanable_state_history_.size() - 1];
    for (const auto& state : row) {
      if (IsExpiredState(state)) {
        consumed_past_deadline = true;
        break;
      }
    }
  }

  if (debug_print) {
    std::string states_str;
    for (const auto& state : GetLatestScanableStates()) {
      states_str += "  " + state.ToString() + "\n";
    }
    XGRAMMAR_LOG(INFO) << "Accepting token id " << token_id << ", string: \""
                       << EscapeString(tokenizer_info_.GetDecodedVocab()[token_id])
                       << "\", current state:\n"
                       << states_str;
  }
  // Handle the stop token
  if (is_stop_token) {
    bool accepted = AcceptStopToken();
    if (debug_print) {
      XGRAMMAR_LOG(INFO) << "The token is an end token. Is accepted: " << accepted;
    }
    return accepted ? FinishAccept(consumed_past_deadline) : false;
  }

  const auto& token = tokenizer_info_.GetDecodedVocab()[token_id];

  const int32_t size_before_token = rule_id_to_completable_states_.size();

  // Phase 1: Try atomic token path (from current state, before byte path)
  std::vector<ParserState> atomic_states;
  std::vector<std::pair<int32_t, ParserState>> atomic_completable;
  std::vector<CaptureEvent> atomic_capture_row;
  bool atomic_completed = false;
  bool atomic_success = AdvanceAtomicToken(token_id, debug_print);
  if (atomic_success) {
    atomic_states = GetLatestScanableStates();
    auto row = rule_id_to_completable_states_.Back();
    atomic_completable.assign(row.data, row.data + row.data_len);
    atomic_capture_row = CopyLastCaptureRow();
    atomic_completed = is_completed_.back();
    PopLastStates(1);
  }

  // Phase 2: Try byte-by-byte path (from the same original state)
  int pos = 0;
  bool byte_path_success = true;
  for (auto char_value : token) {
    if (!Advance(char_value, debug_print)) {
      byte_path_success = false;
      break;
    }
    ++pos;
  }

  // Phase 3: Combine results (no priority — merge with deduplication)
  if (!byte_path_success && !atomic_success) {
    if (debug_print) {
      XGRAMMAR_LOG(INFO) << "Token #" << token_id << "<" << EscapeString(token)
                         << "> rejected at position " << pos;
    }
    PopLastStates(pos);
    return false;
  }

  if (atomic_success && !byte_path_success) {
    PopLastStates(pos);
    AdvanceAtomicToken(token_id, debug_print);
    token_length_history.push_back(1);
    if (ShouldTrackAcceptedBytes()) {
      AppendAtomicRow(token);
    }
  } else if (byte_path_success && !atomic_success) {
    token_length_history.push_back(token.size());
    if (ShouldTrackAcceptedBytes()) {
      AppendPerByteRows(token);
    }
  } else {
    // Both paths succeeded — merge atomic token states into byte path
    if (token.empty()) {
      // Zero-length token: byte path created 0 timepoints, just push atomic states
      scanable_state_history_.PushBack(atomic_states);
      rule_id_to_completable_states_.PushBack(atomic_completable);
      is_completed_.push_back(atomic_completed);
      PushCaptureRow(atomic_capture_row);
      token_length_history.push_back(1);
      if (ShouldTrackAcceptedBytes()) {
        AppendAtomicRow(token);
      }
    } else {
      auto byte_states = GetLatestScanableStates();
      std::vector<ParserState> merged = byte_states;
      StateEqualForParsing state_eq;
      for (const auto& s : atomic_states) {
        if (std::find_if(merged.begin(), merged.end(), [&](const auto& m) {
              return state_eq(m, s);
            }) == merged.end()) {
          merged.push_back(s);
        }
      }

      auto byte_row = rule_id_to_completable_states_.Back();
      std::vector<std::pair<int32_t, ParserState>> merged_completable(
          byte_row.data, byte_row.data + byte_row.data_len
      );
      std::vector<CaptureEvent> merged_capture_row = CopyLastCaptureRow();
      bool byte_completed = is_completed_.back();
      PopLastStates(1);

      for (const auto& cs : atomic_completable) {
        if (std::find_if(merged_completable.begin(), merged_completable.end(), [&](const auto& m) {
              return m.first == cs.first && state_eq(m.second, cs.second);
            }) == merged_completable.end()) {
          merged_completable.push_back(cs);
        }
      }

      for (auto event : atomic_capture_row) {
        // In the atomic path, the after-token position was size_before_token; in the byte path
        // it is the row being re-pushed. Remap events that started at the after-token position
        // (empty spans) so that they stay empty in the byte-path numbering.
        if (event.start_pos == size_before_token) {
          event.start_pos = rule_id_to_completable_states_.size();
        }
        auto existing = std::find_if(
            merged_capture_row.begin(),
            merged_capture_row.end(),
            [&](const CaptureEvent& e) {
              return e.rule_id == event.rule_id && e.start_pos == event.start_pos;
            }
        );
        if (existing == merged_capture_row.end()) {
          merged_capture_row.push_back(event);
        } else {
          existing->hidden_suffix_bytes =
              std::max(existing->hidden_suffix_bytes, event.hidden_suffix_bytes);
          existing->hidden_stop_bytes =
              std::max(existing->hidden_stop_bytes, event.hidden_stop_bytes);
        }
      }

      scanable_state_history_.PushBack(merged);
      rule_id_to_completable_states_.PushBack(merged_completable);
      is_completed_.push_back(byte_completed || atomic_completed);
      PushCaptureRow(merged_capture_row);
      token_length_history.push_back(token.size());
      if (ShouldTrackAcceptedBytes()) {
        AppendPerByteRows(token);
      }
    }
  }

  if (debug_print) {
    XGRAMMAR_LOG(INFO) << "Token #" << token_id << "<" << EscapeString(token) << "> accepted.";
  }
  return FinishAccept(consumed_past_deadline);
}

bool GrammarMatcher::Impl::AcceptString(const std::string& input_str, bool debug_print) {
  if (IsStopTokenAccepted()) {
    XGRAMMAR_LOG(WARNING) << "The matcher has terminated after accepting the stop token, but is "
                          << "trying to accept new string \"" << EscapeString(input_str) << "\".";
    return false;
  }

  if (debug_print) {
    XGRAMMAR_LOG(INFO) << "Trying to accept string \"" << EscapeString(input_str)
                       << "\". Current state:\n"
                       << PrintStates();
  }

  current_token_index_ = static_cast<int32_t>(token_length_history.size());

  // Capture events are only recorded on the definitive accept path.
  CaptureRecordingGuard capture_guard(this);

  int accepted_cnt = 0;
  for (auto char_value : input_str) {
    if (!Advance(char_value, debug_print)) {
      if (debug_print) {
        XGRAMMAR_LOG(INFO) << "String \"" << EscapeString(input_str) << "\" is rejected at "
                           << "position " << accepted_cnt << ", char " << EscapeString(char_value);
      }
      PopLastStates(accepted_cnt);
      return false;
    }
    if (debug_print) {
      XGRAMMAR_LOG(INFO) << "Char " << EscapeString(char_value) << " is accepted. Current state:\n"
                         << PrintStates();
    }
    ++accepted_cnt;
  }
  token_length_history.push_back(input_str.size());
  if (ShouldTrackAcceptedBytes()) {
    AppendPerByteRows(input_str);
  }

  if (debug_print) {
    XGRAMMAR_LOG(INFO) << "String \"" << EscapeString(input_str) << "\" is accepted.";
  }
  return true;
}

std::string GrammarMatcher::Impl::PrintBitmask(
    int32_t* bitmask_data_ptr, const TokenizerInfo& tokenizer_info
) {
  constexpr int kMaxPrintTokens = 100;
  std::vector<int32_t> accepted_ids;
  std::vector<int32_t> rejected_ids;
  auto bitset =
      DynamicBitset(tokenizer_info.GetVocabSize(), reinterpret_cast<uint32_t*>(bitmask_data_ptr));
  for (int i = 0; i < tokenizer_info.GetVocabSize(); ++i) {
    if (bitset[i]) {
      accepted_ids.push_back(i);
    } else {
      rejected_ids.push_back(i);
    }
  }
  std::stringstream ss;
  ss << "TokenBitmask(num_tokens=" << tokenizer_info.GetVocabSize()
     << ", accepted_num=" << accepted_ids.size() << ", rejected_num=" << rejected_ids.size()
     << ",\naccepted_ids=" << PrintTokenByIds(accepted_ids, tokenizer_info, kMaxPrintTokens)
     << ",\nrejected_ids=" << PrintTokenByIds(rejected_ids, tokenizer_info, kMaxPrintTokens) << ")";
  return ss.str();
}

bool GrammarMatcher::Impl::IsTokenBitmaskAllTrue(int32_t* bitmask_data_ptr) {
  DynamicBitset next_token_bitset(
      tokenizer_info_.GetVocabSize(), reinterpret_cast<uint32_t*>(bitmask_data_ptr)
  );
  return next_token_bitset.All();
}

bool GrammarMatcher::Impl::FillNextTokenBitmask(
    DLTensor* next_token_bitmask, int index, bool debug_print
) {
  XGRAMMAR_CHECK(!IsStopTokenAccepted())
      << "GrammarMatcher has terminated after accepting the stop token, but is trying to "
         "find the next token mask";
  int32_t* bitmask_data_ptr =
      CheckAndGetBitmaskPtr(*next_token_bitmask, tokenizer_info_.GetVocabSize(), index);
  current_token_index_ = static_cast<int32_t>(token_length_history.size());
  if (has_budget_rules_) {
    const auto& row = scanable_state_history_[scanable_state_history_.size() - 1];
    bool any_expired = false;
    bool any_alive = false;
    bool can_force_close_without_marker = false;
    for (const auto& state : row) {
      if (IsExpiredState(state)) {
        any_expired = true;
        can_force_close_without_marker =
            can_force_close_without_marker ||
            (has_budget_marker_rules_ && CanForceCompleteWithoutMarker(state));
      } else {
        any_alive = true;
      }
    }
    if (can_force_close_without_marker) {
      // Compute the enforcing state on a copy. In addition to dropping expired derivations,
      // this lets a budgeted suffix/stop rule end through its body when the marker has not
      // appeared yet. The real state is committed only after an allowed token is accepted.
      Impl trial(*this);
      trial.capture_recording_ = false;
      bool applied = trial.ApplyBudgetEnforcement(debug_print);
      if (applied) {
        trial.FillBitmaskForStates(bitmask_data_ptr, index, /*skip_expired=*/false, debug_print);
      }
      if (applied && (trial.IsCompleted() || trial.BitmaskHasAnyToken(bitmask_data_ptr))) {
        budget_enforce_pending_ = true;
        budget_force_close_pending_ = true;
        return !IsTokenBitmaskAllTrue(bitmask_data_ptr);
      }
    }
    if (any_expired && (any_alive || IsCompleted())) {
      // No marker-less completion is needed: retain the original max_tokens fast path.
      FillBitmaskForStates(bitmask_data_ptr, index, /*skip_expired=*/true, debug_print);
      if (BitmaskHasAnyToken(bitmask_data_ptr) || IsCompleted()) {
        budget_enforce_pending_ = true;
        budget_force_close_pending_ = false;
        return !IsTokenBitmaskAllTrue(bitmask_data_ptr);
      }
    }
    // No enforcement at this position: either no budget has expired, or the expired
    // derivations cannot end here — relax the budget for one step and report it on the next
    // accept.
    budget_enforce_pending_ = false;
    budget_force_close_pending_ = false;
  }
  FillBitmaskForStates(bitmask_data_ptr, index, /*skip_expired=*/false, debug_print);
  return !IsTokenBitmaskAllTrue(bitmask_data_ptr);
}

void GrammarMatcher::Impl::FillBitmaskForStates(
    int32_t* bitmask_data_ptr, int index, bool skip_expired, bool debug_print
) {
  const auto& sorted_decoded_vocab = tokenizer_info_.GetSortedDecodedVocab();
  const auto& subtree_range = tokenizer_info_.GetTrieSubtreeNodesRange();
  const auto& adaptive_token_mask_cache = compiled_grammar_->adaptive_token_mask_cache;
  // We need to have a copy, because scanable_state_history_ will be modified during the
  // FillNextTokenBitmask process, which can lead to undefined behavior.
  std::vector<ParserState> latest_states;
  for (const auto& state : scanable_state_history_[scanable_state_history_.size() - 1]) {
    if (skip_expired && IsExpiredState(state)) {
      continue;
    }
    latest_states.push_back(state);
  }

  // We check all the latest states of the earley parser, and check all the masks of the leaf
  // states. The final accepted token set is the union of the accepted token sets of all leaf
  // states. The final rejected token set is the intersection of the rejected token sets of all leaf
  // states.

  // Note these indices store the indices in sorted_decoded_vocab, instead of the token ids.
  tmp_accepted_bitset_.Reset();
  // {-1} means the universal set, i.e. all tokens initially
  tmp_rejected_indices_.assign({-1});

  if (debug_print) {
    XGRAMMAR_LOG(INFO) << "FillNextTokenBitmask: index=" << index
                       << ", num of states=" << latest_states.size();
  }

  std::vector<std::pair<ParserState, decltype(adaptive_token_mask_cache.cbegin())>>
      latest_states_with_masks;

  for (const auto& state : latest_states) {
    auto adaptive_token_mask_it = adaptive_token_mask_cache.find(state);
    XGRAMMAR_CHECK(adaptive_token_mask_it != adaptive_token_mask_cache.end()) << state;
    const auto& adaptive_token_mask = adaptive_token_mask_it->second;
    latest_states_with_masks.push_back(std::make_pair(state, adaptive_token_mask_it));
    if (adaptive_token_mask.store_type == StoreType::kAcceptedBitset) {
      tmp_accepted_bitset_ |= adaptive_token_mask.accepted_bitset;
    } else if (adaptive_token_mask.store_type == StoreType::kAccepted) {
      for (auto idx : adaptive_token_mask.accepted_indices) {
        tmp_accepted_bitset_.Set(sorted_decoded_vocab[idx].first, true);
      }
    }
  }

  for (const auto& [state, adaptive_token_mask_it] : latest_states_with_masks) {
    const auto& adaptive_token_mask = adaptive_token_mask_it->second;

    // For each ParserState, we will check every uncertain token and put them into the accepted or
    // rejected list.

    // Step 2. Update the accepted tokens in accepted_indices_delta, or the rejected tokens in
    // rejected_indices_delta.

    // If the accepted tokens are saved, it means it is likely to be smaller than the rejected
    // tokens, so we will just find the accepted tokens, and vice versa.

    tmp_rejected_indices_delta_.clear();

    // Examine only the current one ParserState
    PushOneStateToCheck(state);

    const std::string* prev_token = nullptr;
    int prev_matched_size = 0;
    if (debug_print) {
      XGRAMMAR_LOG(INFO) << "The ParserState is " << state << ", the mask is "
                         << adaptive_token_mask.Print(tokenizer_info_);
    }
    int last_rejected_uncertain_range = 0;
    for (const auto& cur_token_idx : adaptive_token_mask.uncertain_indices) {
      // Check if the current token is already accepted. If it is, we can skip it.
      if (tmp_accepted_bitset_[sorted_decoded_vocab[cur_token_idx].first]) {
        continue;
      }

      // Check if the current token is in the rejected range. i.e. check if the current token
      // is on the subtree of the rejected token.
      if (cur_token_idx < last_rejected_uncertain_range) {
        if (adaptive_token_mask.store_type == StoreType::kRejected) {
          tmp_rejected_indices_delta_.push_back(cur_token_idx);
        }
        continue;
      }

      const auto& cur_token = sorted_decoded_vocab[cur_token_idx].second;
      bool accepted = true;

      // Step 2.1. Find the longest common prefix with the accepted part of the previous token.
      // We can reuse the previous matched size to avoid unnecessary matching.
      if (prev_token) {
        int lcp_len = std::mismatch(
                          cur_token.begin(), cur_token.end(), prev_token->begin(), prev_token->end()
                      )
                          .first -
                      cur_token.begin();
        if (lcp_len > prev_matched_size) {
          last_rejected_uncertain_range = subtree_range[cur_token_idx];
          accepted = false;
        } else if (lcp_len < prev_matched_size) {
          PopLastStates(prev_matched_size - lcp_len);
        }
        prev_matched_size = std::min(prev_matched_size, lcp_len);
      }

      // Step 2.2. Find if the current token is accepted or rejected.
      if (accepted) {
        for (int j = prev_matched_size; j < static_cast<int>(cur_token.size()); ++j) {
          if (!Advance(cur_token[j])) {
            last_rejected_uncertain_range = subtree_range[cur_token_idx];
            accepted = false;
            break;
          }
          prev_matched_size = j + 1;
        }
      }

      // Step 2.3. Push the result to the delta list.
      if (adaptive_token_mask.store_type == StoreType::kAcceptedBitset ||
          adaptive_token_mask.store_type == StoreType::kAccepted) {
        if (accepted) {
          tmp_accepted_bitset_.Set(sorted_decoded_vocab[cur_token_idx].first, true);
        }
      } else {
        if (!accepted) {
          tmp_rejected_indices_delta_.push_back(cur_token_idx);
        }
      }

      prev_token = &cur_token;
    }

    PopLastStates(prev_matched_size + 1);
    // Step 3. Update the accepted_indices or rejected_indices
    if (adaptive_token_mask.store_type == StoreType::kRejected) {
      // rejected_indices = Intersect(
      //     rejected_indices,
      //     adaptive_token_mask.rejected_indices + rejected_indices_delta)
      IntsetUnion(&tmp_rejected_indices_delta_, adaptive_token_mask.rejected_indices);
      IntsetIntersection(&tmp_rejected_indices_, tmp_rejected_indices_delta_);
    }
  }

  // Finally update the rejected_ids bitset
  bool can_reach_end = IsCompleted();
  SetTokenBitmask(
      bitmask_data_ptr, tmp_accepted_bitset_, tmp_rejected_indices_, can_reach_end, false
  );
  if (debug_print) {
    XGRAMMAR_LOG(INFO) << "Filled bitmask: " << PrintBitmask(bitmask_data_ptr, tokenizer_info_);
  }
}

std::string GrammarMatcher::Impl::FindJumpForwardString() {
  XGRAMMAR_CHECK(!IsStopTokenAccepted())
      << "GrammarMatcher has terminated after accepting the stop token, but is trying to "
         "get the jump forward string";

  current_token_index_ = static_cast<int32_t>(token_length_history.size());
  if (budget_force_close_pending_) {
    Impl trial(*this);
    trial.capture_recording_ = false;
    if (trial.ApplyBudgetEnforcement()) {
      trial.budget_enforce_pending_ = false;
      trial.budget_force_close_pending_ = false;
      return trial.FindJumpForwardString();
    }
  }

  std::string result;
  int num_accepted_chars = 0;
  bool can_find_next_char = true;

  while (can_find_next_char) {
    const auto& states = scanable_state_history_[scanable_state_history_.size() - 1];

    // The state comes to the end of the grammar
    if (IsCompleted()) {
      can_find_next_char = false;
      break;
    }

    // 1. Check that for every leaf ParserState, the next possible char is unique and the same
    // -1 means not found yet; 0~255 means the next char
    int next_char = -1;
    for (const auto& state : states) {
      if (budget_enforce_pending_ && IsExpiredState(state)) {
        continue;
      }
      XGRAMMAR_DCHECK(state.rule_id != -1 && grammar_->per_rule_fsms[state.rule_id].has_value());
      const auto& fsm = grammar_->per_rule_fsms[state.rule_id].value();
      const auto& current_edges = fsm.GetFsm().GetFsm().GetEdges(state.element_id);
      for (const auto& edge : current_edges) {
        if (!edge.IsCharRange()) {
          continue;
        }
        if (edge.min != edge.max) {
          can_find_next_char = false;
          break;
        }
        if (next_char == -1) {
          next_char = edge.min;
        } else if (next_char != edge.min) {
          can_find_next_char = false;
          break;
        }
      }
    }

    if (next_char == -1) {
      can_find_next_char = false;
    }

    // 2. If found, accept the char and iterate to the next position
    if (can_find_next_char) {
      result += static_cast<uint8_t>(next_char);
      Advance(next_char);
      ++num_accepted_chars;
    }
  }

  // Rollback all chars accepted
  PopLastStates(num_accepted_chars);
  return result;
}

void GrammarMatcher::Impl::Rollback(int num_tokens) {
  XGRAMMAR_CHECK(num_tokens <= static_cast<int>(token_length_history.size()))
      << "Intended to rollback " << num_tokens << " tokens, but only the last "
      << token_length_history.size() << " steps of history are saved";
  while (num_tokens > 0) {
    int steps = token_length_history.back();
    PopLastStates(steps);
    token_length_history.pop_back();
    if (ShouldTrackAcceptedBytes() && steps > 0) {
      row_byte_end_.resize(row_byte_end_.size() - steps);
      accepted_bytes_.resize(row_byte_end_.back());
    }
    --num_tokens;
  }
  budget_enforce_pending_ = false;
  budget_force_close_pending_ = false;
  budget_body_match_cache_.clear();
}

std::vector<std::pair<std::string, std::string>> GrammarMatcher::Impl::GetCaptures(bool deduplicate
) const {
  std::vector<std::pair<std::string, std::string>> result;
  if (!IsCaptureTrackingEnabled()) {
    return result;
  }
  XGRAMMAR_DCHECK(capture_event_history_.size() == static_cast<int32_t>(row_byte_end_.size()))
      << "The capture history is not aligned with the byte history: "
      << capture_event_history_.size() << " vs " << row_byte_end_.size();

  // Flatten the event history. Events are ordered by completion position, and by completion
  // order within a position.
  struct FlatEvent {
    int32_t rule_id;
    int32_t start_row;
    int32_t end_row;
    int32_t hidden_suffix_bytes;
    int32_t hidden_stop_bytes;
    bool marker_present = false;
    int64_t marker_start_byte = -1;
  };
  std::vector<FlatEvent> events;
  for (int32_t row = 0; row < capture_event_history_.size(); ++row) {
    for (const auto& event : capture_event_history_[row]) {
      int32_t start_row = event.start_pos == ParserState::kNoPrevInputPos ? 0 : event.start_pos;
      XGRAMMAR_DCHECK(start_row <= row);
      events.push_back(
          {event.rule_id,
           start_row,
           row,
           event.hidden_suffix_bytes,
           event.hidden_stop_bytes,
           false,
           -1}
      );
    }
  }

  // The Earley parser explores all parse hypotheses in parallel, so one occurrence of a rule
  // (identified by its rule id and start position) may complete at several candidate end
  // positions before the following input decides the real one. When deduplicate is true, we
  // keep only the last (longest) completion of each occurrence.
  std::vector<bool> keep(events.size(), true);
  if (deduplicate) {
    std::unordered_map<int64_t, size_t> last_index;
    for (size_t i = 0; i < events.size(); ++i) {
      int64_t key = (static_cast<int64_t>(events[i].rule_id) << 32) |
                    static_cast<uint32_t>(events[i].start_row);
      auto it = last_index.find(key);
      if (it != last_index.end()) {
        keep[it->second] = false;
        it->second = i;
      } else {
        last_index[key] = i;
      }
    }
  }

  auto contains_end_state = [](const CompactFSMWithStartEnd& fsm,
                               const std::unordered_set<int>& states) {
    return std::any_of(states.begin(), states.end(), [&](int state) {
      return fsm.IsEndState(state);
    });
  };

  auto accepted_prefixes = [&](const CompactFSMWithStartEnd& fsm, int64_t begin, int64_t end) {
    XGRAMMAR_DCHECK(fsm.IsLeaf()) << "A suffix/stop capture helper must compile to a leaf FSM";
    std::vector<bool> result(static_cast<size_t>(end - begin + 1), false);
    std::unordered_set<int> states{fsm.GetStart()};
    fsm.GetFsm().GetEpsilonClosure(&states);
    result[0] = contains_end_state(fsm, states);
    std::unordered_set<int> next_states;
    for (int64_t offset = 0; offset < end - begin; ++offset) {
      fsm.GetFsm().Advance(
          states, accepted_bytes_[begin + offset], &next_states, FSMEdge::EdgeType::kCharRange, true
      );
      states = next_states;
      result[static_cast<size_t>(offset + 1)] = contains_end_state(fsm, states);
    }
    return result;
  };

  // Compute which suffixes of [begin, end) are accepted by marker_fsm. This is a reverse NFA
  // traversal, so locating a delimiter remains linear in the captured byte length even when the
  // body (for example /.*/) can end at every byte.
  auto accepted_suffixes = [&](const CompactFSMWithStartEnd& marker_fsm, int64_t begin, int64_t end
                           ) {
    XGRAMMAR_DCHECK(marker_fsm.IsLeaf())
        << "A suffix/stop marker helper must compile to a leaf FSM";
    const auto& fsm = marker_fsm.GetFsm();
    std::unordered_set<int> reachable;
    marker_fsm.GetReachableStates(&reachable);
    struct ReverseCharEdge {
      int32_t source;
      int32_t min;
      int32_t max;
    };
    std::vector<std::vector<int32_t>> reverse_epsilon(fsm.NumStates());
    std::vector<std::vector<ReverseCharEdge>> reverse_char(fsm.NumStates());
    for (int32_t source : reachable) {
      for (const auto& edge : fsm.GetEdges(source)) {
        if (!reachable.count(edge.target)) {
          continue;
        }
        if (edge.IsEpsilon()) {
          reverse_epsilon[edge.target].push_back(source);
        } else if (edge.IsCharRange()) {
          reverse_char[edge.target].push_back({source, edge.min, edge.max});
        }
      }
    }
    auto add_reverse_epsilon_closure = [&](std::unordered_set<int>* states) {
      std::vector<int32_t> queue(states->begin(), states->end());
      for (size_t i = 0; i < queue.size(); ++i) {
        for (int32_t predecessor : reverse_epsilon[queue[i]]) {
          if (states->insert(predecessor).second) {
            queue.push_back(predecessor);
          }
        }
      }
    };

    std::vector<bool> result(static_cast<size_t>(end - begin + 1), false);
    std::unordered_set<int> states(marker_fsm.GetEnds().begin(), marker_fsm.GetEnds().end());
    add_reverse_epsilon_closure(&states);
    result[static_cast<size_t>(end - begin)] = states.count(marker_fsm.GetStart()) != 0;
    std::unordered_set<int> previous_states;
    for (int64_t offset = end - begin; offset > 0; --offset) {
      previous_states.clear();
      int32_t byte = accepted_bytes_[begin + offset - 1];
      for (int32_t target : states) {
        for (const auto& edge : reverse_char[target]) {
          if (edge.min <= byte && byte <= edge.max) {
            previous_states.insert(edge.source);
          }
        }
      }
      add_reverse_epsilon_closure(&previous_states);
      states = previous_states;
      result[static_cast<size_t>(offset - 1)] = states.count(marker_fsm.GetStart()) != 0;
    }
    return result;
  };

  // Resolve every marker to a concrete byte span once. Fixed strings use their recorded length;
  // regexes and named terminals use helper FSMs for both sides of the original body/marker split.
  for (size_t i = 0; i < events.size(); ++i) {
    if (!keep[i]) {
      continue;
    }
    auto& event = events[i];
    int32_t hidden_bytes = std::max(event.hidden_suffix_bytes, event.hidden_stop_bytes);
    if (hidden_bytes <= 0) {
      continue;
    }
    const auto& rule = grammar_->GetRule(event.rule_id);
    const auto* suffix_stop_info = grammar_->GetSuffixStopInfo(event.rule_id);
    XGRAMMAR_DCHECK(suffix_stop_info != nullptr);
    int64_t event_start = row_byte_end_[event.start_row];
    int64_t event_end = row_byte_end_[event.end_row];
    event.marker_present = true;
    if (suffix_stop_info->body_rule_id == -1) {
      event.marker_start_byte =
          std::max(event_start, event_end - static_cast<int64_t>(hidden_bytes));
      continue;
    }

    XGRAMMAR_DCHECK(suffix_stop_info->body_rule_id >= 0 && suffix_stop_info->marker_rule_id >= 0);
    XGRAMMAR_DCHECK(
        grammar_->per_rule_fsms[suffix_stop_info->body_rule_id].has_value() &&
        grammar_->per_rule_fsms[suffix_stop_info->marker_rule_id].has_value()
    );
    const auto& body_fsm = grammar_->per_rule_fsms[suffix_stop_info->body_rule_id]->GetFsm();
    const auto& marker_fsm = grammar_->per_rule_fsms[suffix_stop_info->marker_rule_id]->GetFsm();
    std::vector<bool> body_ends = accepted_prefixes(body_fsm, event_start, event_end);
    std::vector<bool> marker_starts = accepted_suffixes(marker_fsm, event_start, event_end);
    bool found = false;
    for (size_t offset = 0; offset < body_ends.size(); ++offset) {
      if (body_ends[offset] && marker_starts[offset]) {
        event.marker_start_byte = event_start + static_cast<int64_t>(offset);
        found = true;
        break;
      }
    }
    XGRAMMAR_DCHECK(found) << "Could not recover the suffix/stop marker boundary for rule "
                           << rule.name;
    if (!found) {
      event.marker_present = false;
      event.marker_start_byte = -1;
    }
  }

  // A stop marker is excluded from every capture containing it. Build the concrete byte spans
  // once, then splice them out while materializing each capture. Duplicate/overlapping spans can
  // arise from equivalent Earley hypotheses, so merge them defensively.
  std::vector<std::pair<int64_t, int64_t>> hidden_stop_spans;
  for (size_t i = 0; i < events.size(); ++i) {
    if (!keep[i] || events[i].hidden_stop_bytes <= 0 || !events[i].marker_present) {
      continue;
    }
    int64_t event_end = row_byte_end_[events[i].end_row];
    int64_t hidden_start = events[i].marker_start_byte;
    if (hidden_start < event_end) {
      hidden_stop_spans.emplace_back(hidden_start, event_end);
    }
  }
  std::sort(hidden_stop_spans.begin(), hidden_stop_spans.end());
  std::vector<std::pair<int64_t, int64_t>> merged_hidden_stop_spans;
  for (const auto& span : hidden_stop_spans) {
    if (!merged_hidden_stop_spans.empty() && span.first <= merged_hidden_stop_spans.back().second) {
      merged_hidden_stop_spans.back().second =
          std::max(merged_hidden_stop_spans.back().second, span.second);
    } else {
      merged_hidden_stop_spans.push_back(span);
    }
  }

  for (size_t i = 0; i < events.size(); ++i) {
    if (!keep[i]) {
      continue;
    }
    const auto& event = events[i];
    const auto& rule = grammar_->GetRule(event.rule_id);
    const auto* suffix_stop_info = grammar_->GetSuffixStopInfo(event.rule_id);
    int64_t capture_start = row_byte_end_[event.start_row];
    int64_t capture_end = row_byte_end_[event.end_row];
    if (event.marker_present && suffix_stop_info != nullptr &&
        !suffix_stop_info->stop_capture_name.empty()) {
      std::string marker_capture;
      if (event.marker_start_byte < capture_end) {
        marker_capture.assign(
            reinterpret_cast<const char*>(accepted_bytes_.data() + event.marker_start_byte),
            static_cast<size_t>(capture_end - event.marker_start_byte)
        );
      }
      result.emplace_back(suffix_stop_info->stop_capture_name, std::move(marker_capture));
    }
    if (rule.capture_name.empty()) {
      continue;
    }
    if (event.hidden_suffix_bytes > 0 && event.marker_present) {
      capture_end = event.marker_start_byte;
    }

    std::string capture;
    int64_t cursor = capture_start;
    auto append_bytes = [&](int64_t begin, int64_t end) {
      if (begin < end) {
        capture.append(
            reinterpret_cast<const char*>(accepted_bytes_.data() + begin),
            static_cast<size_t>(end - begin)
        );
      }
    };
    for (const auto& hidden : merged_hidden_stop_spans) {
      if (hidden.second <= capture_start) {
        continue;
      }
      if (hidden.first >= capture_end) {
        break;
      }
      int64_t hidden_begin = std::max(hidden.first, capture_start);
      int64_t hidden_end = std::min(hidden.second, capture_end);
      append_bytes(cursor, hidden_begin);
      cursor = std::max(cursor, hidden_end);
    }
    append_bytes(cursor, capture_end);
    result.emplace_back(rule.capture_name, std::move(capture));
  }
  return result;
}

void GrammarMatcher::Impl::SetTokenBitmask(
    int32_t* bitmask_data_ptr,
    const DynamicBitset& accepted_bitset,
    const std::vector<int32_t>& rejected_indices,
    bool can_reach_end,
    bool allow_special_token
) {
  // next_token_bitmask = set(all accepted tokens) =
  // 1. all_tokens - (rejected_ids / accepted_ids)
  //    (when rejected_ids != {-1}, i.e. rejected_ids is not the universal set)
  // 2. accepted_ids
  //    (otherwise, when rejected_ids is the universal set)
  DynamicBitset next_token_bitset(
      tokenizer_info_.GetVocabSize(), reinterpret_cast<uint32_t*>(bitmask_data_ptr)
  );
  const auto& sorted_decoded_vocab = tokenizer_info_.GetSortedDecodedVocab();

  if (rejected_indices.size() == 1 && rejected_indices[0] == -1) {
    // If rejected_indices is the universal set, the final accepted token set is just
    // accepted_indices
    next_token_bitset = accepted_bitset;

    if (allow_special_token) {
      for (int id : tokenizer_info_.GetSpecialTokenIds()) {
        next_token_bitset.Set(id, true);
      }
    }

    if (can_reach_end) {
      // add end tokens
      for (int id : stop_token_ids_) {
        next_token_bitset.Set(id, true);
      }
    }
  } else {
    // Otherwise, the final rejected token set is (rejected_indices \ accepted_indices)
    next_token_bitset.Set();

    for (auto i : rejected_indices) {
      auto id = sorted_decoded_vocab[i].first;
      if (!accepted_bitset[id]) {
        next_token_bitset.Set(id, false);
      }
    }
    if (!allow_special_token) {
      for (int id : tokenizer_info_.GetSpecialTokenIds()) {
        next_token_bitset.Set(id, false);
      }
    }
    if (!can_reach_end) {
      for (int id : stop_token_ids_) {
        next_token_bitset.Set(id, false);
      }
    }
  }
}

int GrammarMatcher::Impl::GetNextUncertainToken(
    bool is_uncertain_saved,
    int* iterator_uncertain,
    const std::vector<int>& uncertain_indices,
    const std::vector<bool>& uncertain_tokens_bitset
) {
  if (is_uncertain_saved) {
    ++*iterator_uncertain;
    if (*iterator_uncertain == static_cast<int>(uncertain_indices.size())) {
      return -1;
    }
    return uncertain_indices[*iterator_uncertain];
  } else {
    ++*iterator_uncertain;
    while (*iterator_uncertain < static_cast<int>(uncertain_tokens_bitset.size()) &&
           !uncertain_tokens_bitset[*iterator_uncertain]) {
      ++*iterator_uncertain;
    }
    if (*iterator_uncertain == static_cast<int>(uncertain_tokens_bitset.size())) {
      return -1;
    }
    return *iterator_uncertain;
  }
}

void BatchGrammarMatcher::Impl::BatchFillNextTokenBitmask(
    std::vector<GrammarMatcher>* matchers,
    DLTensor* next_token_bitmask,
    const std::optional<std::vector<int32_t>>& indices,
    bool debug_print
) {
  XGRAMMAR_CHECK(!indices.has_value() || indices->size() == matchers->size())
      << "The size of indices (" << (indices.has_value() ? indices->size() : 0)
      << ") should be the same as the size of matchers (" << matchers->size() << ").";
  // Initialize the thread pool if needed. It should be initialized each time,
  // because ThreadPool cannot be reused after Join().
  if (max_threads_ > 1) {
    thread_pool_.emplace(max_threads_);
  }
  if (!thread_pool_.has_value()) {
    for (int i = 0; i < static_cast<int32_t>(matchers->size()); i++) {
      auto& matcher = (*matchers)[i];
      int index = indices.has_value() ? (*indices)[i] : i;
      XGRAMMAR_CHECK(index >= 0 && index < next_token_bitmask->shape[0])
          << "The index " << index << " is out of range [0, " << next_token_bitmask->shape[0]
          << ") for batch_id " << i << ".";
      matcher->FillNextTokenBitmask(next_token_bitmask, index, debug_print);
    }
  } else {
    auto fill_next_token_mask = [&](int32_t batch_id) {
      auto& matcher = (*matchers)[batch_id];
      int index = indices.has_value() ? (*indices)[batch_id] : batch_id;
      XGRAMMAR_CHECK(index >= 0 && index < next_token_bitmask->shape[0])
          << "The index " << index << " is out of range [0, " << next_token_bitmask->shape[0]
          << ") for batch_id " << batch_id << ".";
      matcher->FillNextTokenBitmask(next_token_bitmask, index, debug_print);
    };
    for (int i = 0; i < static_cast<int32_t>(matchers->size()); i++) {
      thread_pool_->Execute([fill_next_token_mask, i]() { fill_next_token_mask(i); });
    }
    thread_pool_->Join();
  }
}

std::vector<uint8_t> BatchGrammarMatcher::Impl::BatchAcceptString(
    std::vector<GrammarMatcher>* matchers,
    const std::vector<std::string>& input_strs,
    bool debug_print
) {
  XGRAMMAR_CHECK(matchers->size() == input_strs.size())
      << "The size of matchers (" << matchers->size() << ") and input_strs (" << input_strs.size()
      << ") should be the same.";
  std::vector<uint8_t> accepted(matchers->size());
  for (int i = 0; i < static_cast<int32_t>(matchers->size()); i++) {
    auto& matcher = (*matchers)[i];
    accepted[i] = matcher->AcceptString(input_strs[i], debug_print);
  }
  return accepted;
}

std::vector<uint8_t> BatchGrammarMatcher::Impl::BatchAcceptToken(
    std::vector<GrammarMatcher>* matchers, const std::vector<int32_t>& token_ids, bool debug_print
) {
  XGRAMMAR_CHECK(matchers->size() == token_ids.size())
      << "The size of matchers (" << matchers->size() << ") and token_ids (" << token_ids.size()
      << ") should be the same.";
  std::vector<uint8_t> accepted(matchers->size());
  for (int i = 0; i < static_cast<int32_t>(matchers->size()); i++) {
    auto& matcher = (*matchers)[i];
    accepted[i] = matcher->AcceptToken(token_ids[i], debug_print);
  }
  return accepted;
}

void BatchGrammarMatcher::Impl::BatchRollback(
    std::vector<GrammarMatcher>* matchers, const std::vector<int>& num_tokens
) {
  XGRAMMAR_CHECK(matchers->size() == num_tokens.size())
      << "The size of matchers (" << matchers->size() << ") and num_tokens (" << num_tokens.size()
      << ") should be the same.";
  for (int i = 0; i < static_cast<int32_t>(matchers->size()); i++) {
    (*matchers)[i].Rollback(num_tokens[i]);
  }
}

GrammarMatcher::GrammarMatcher(
    const CompiledGrammar& compiled_grammar,
    std::optional<std::vector<int>> override_stop_tokens,
    bool terminate_without_stop_token,
    int max_rollback_tokens
)
    : pimpl_(std::make_shared<GrammarMatcher::Impl>(
          compiled_grammar, override_stop_tokens, terminate_without_stop_token, max_rollback_tokens
      )) {}

bool GrammarMatcher::AcceptToken(int32_t token_id, bool debug_print) {
  return pimpl_->AcceptToken(token_id, debug_print);
}

bool GrammarMatcher::AcceptString(const std::string& input_str, bool debug_print) {
  return pimpl_->AcceptString(input_str, debug_print);
}

bool GrammarMatcher::FillNextTokenBitmask(
    DLTensor* next_token_bitmask, int index, bool debug_print
) {
  return pimpl_->FillNextTokenBitmask(next_token_bitmask, index, debug_print);
}

bool GrammarMatcher::TraverseDraftTree(
    const DLTensor* retrieve_next_token,
    const DLTensor* retrieve_next_sibling,
    const DLTensor* draft_tokens,
    DLTensor* token_bitmask,
    double time_threshold
) {
  auto check_cpu = [](const DLTensor* tensor, const char* name) {
    XGRAMMAR_CHECK(
        tensor->device.device_type == kDLCPU || tensor->device.device_type == kDLCUDAHost ||
        tensor->device.device_type == kDLROCMHost
    ) << "The "
      << name << " tensor must be on CPU";
  };

  XGRAMMAR_CHECK(
      retrieve_next_token->ndim == 1 && retrieve_next_token->dtype.code == kDLInt &&
      retrieve_next_token->dtype.bits == 64
  ) << "The retrieve_next_token tensor must be a 1D int64 tensor";
  XGRAMMAR_CHECK(
      retrieve_next_sibling->ndim == 1 && retrieve_next_sibling->dtype.code == kDLInt &&
      retrieve_next_sibling->dtype.bits == 64
  ) << "The retrieve_next_sibling tensor must be a 1D int64 tensor";
  XGRAMMAR_CHECK(
      draft_tokens->ndim == 1 && draft_tokens->dtype.code == kDLInt &&
      draft_tokens->dtype.bits == 64
  ) << "The draft_tokens tensor must be a 1D int64 tensor";
  XGRAMMAR_CHECK(
      token_bitmask->ndim == 2 && token_bitmask->dtype.code == kDLInt &&
      token_bitmask->dtype.bits == 32
  ) << "The token_bitmask tensor must be a 2D int32 tensor";

  check_cpu(retrieve_next_token, "retrieve_next_token");
  check_cpu(retrieve_next_sibling, "retrieve_next_sibling");
  check_cpu(draft_tokens, "draft_tokens");
  check_cpu(token_bitmask, "token_bitmask");

  XGRAMMAR_CHECK(retrieve_next_token->shape[0] == retrieve_next_sibling->shape[0])
      << "The retrieve_next_token and retrieve_next_sibling tensors must have the same length";
  XGRAMMAR_CHECK(retrieve_next_token->shape[0] == draft_tokens->shape[0])
      << "The retrieve_next_token and draft_tokens tensors must have the same length";
  XGRAMMAR_CHECK(retrieve_next_token->shape[0] == token_bitmask->shape[0])
      << "The token_bitmask batch size must match the number of nodes in the tree";
  XGRAMMAR_CHECK(retrieve_next_sibling->shape[0] > 0 && retrieve_next_sibling->data != nullptr)
      << "The draft tree must not be empty";
  XGRAMMAR_CHECK(reinterpret_cast<const int64_t*>(retrieve_next_sibling->data)[0] == -1)
      << "The root node must not have siblings";

  return details::TraverseDraftTreeRecursive(
      0,
      -1,
      reinterpret_cast<const int64_t*>(retrieve_next_token->data),
      reinterpret_cast<const int64_t*>(retrieve_next_sibling->data),
      reinterpret_cast<const int64_t*>(draft_tokens->data),
      *this,
      token_bitmask,
      time_threshold,
      details::Clock::now()
  );
}

std::string GrammarMatcher::FindJumpForwardString() { return pimpl_->FindJumpForwardString(); }

void GrammarMatcher::Rollback(int num_tokens) { pimpl_->Rollback(num_tokens); }

std::vector<std::pair<std::string, std::string>> GrammarMatcher::GetCaptures(bool deduplicate
) const {
  return pimpl_->GetCaptures(deduplicate);
}

bool GrammarMatcher::IsTerminated() const { return pimpl_->IsTerminated(); }

bool GrammarMatcher::IsCompleted() const { return pimpl_->IsCompleted(); }

void GrammarMatcher::Reset() { pimpl_->Reset(); }

GrammarMatcher GrammarMatcher::Fork() const {
  return GrammarMatcher(std::make_shared<Impl>(*pimpl_));
}

int GrammarMatcher::GetMaxRollbackTokens() const { return pimpl_->GetMaxRollbackTokens(); }

const std::vector<int>& GrammarMatcher::GetStopTokenIds() const {
  return pimpl_->GetStopTokenIds();
}

std::string GrammarMatcher::_DebugPrintInternalState() const {
  return pimpl_->_DebugPrintInternalState();
}

void BatchGrammarMatcher::BatchFillNextTokenBitmask(
    std::vector<GrammarMatcher>* matchers,
    DLTensor* next_token_bitmask,
    const std::optional<std::vector<int32_t>>& indices,
    bool debug_print
) {
  return pimpl_->BatchFillNextTokenBitmask(matchers, next_token_bitmask, indices, debug_print);
}

std::vector<uint8_t> BatchGrammarMatcher::BatchAcceptString(
    std::vector<GrammarMatcher>* matchers,
    const std::vector<std::string>& input_strs,
    bool debug_print
) {
  return Impl::BatchAcceptString(matchers, input_strs, debug_print);
}

std::vector<uint8_t> BatchGrammarMatcher::BatchAcceptToken(
    std::vector<GrammarMatcher>* matchers, const std::vector<int32_t>& token_ids, bool debug_print
) {
  return Impl::BatchAcceptToken(matchers, token_ids, debug_print);
}

void BatchGrammarMatcher::BatchRollback(
    std::vector<GrammarMatcher>* matchers, const std::vector<int>& num_tokens
) {
  Impl::BatchRollback(matchers, num_tokens);
}

BatchGrammarMatcher::BatchGrammarMatcher(std::variant<std::string, int32_t> max_threads)
    : pimpl_(std::make_shared<BatchGrammarMatcher::Impl>(max_threads)) {}

}  // namespace xgrammar
