name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
title: "[Bug] "
labels: ['Bug']

body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: 1. I have searched related issues but cannot get the expected help.
        - label: 2. The bug has not been fixed in the latest version.
        - label: 3. I have filled all the required information below.
        - label: 4. The bug report is in English.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        Please include a minimal code snippet to reproduce the behavior.
      placeholder: |
        A placeholder for the command.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide the version of XGrammar, the serving engine for llms, etc.
      placeholder: Environment here.
    validations:
      required: true
