#!/usr/bin/env bash
set -euo pipefail

# Update `rust/submodules.toml` from the repo's `.gitmodules` + `git submodule status`.
#
# Why:
#   - crates.io packages do not include git submodule contents
#   - rust/build.rs needs deterministic pins (url + rev) to fetch missing submodules
#
# Usage:
#   bash scripts/update_rust_submodules.sh

root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${root}" ]]; then
  echo "error: must be run inside a git checkout" >&2
  exit 1
fi

cd "${root}"

out="rust/submodules.toml"
tmp="$(mktemp "${TMPDIR:-/tmp}/xgrammar-submodules.XXXXXX")"
trap 'rm -f "${tmp}"' EXIT

# `git submodule status` is our source-of-truth for pinned SHAs (gitlinks).
# Note: lines may prefix the SHA with '-', '+', or 'U' depending on state.
sub_status="$(git submodule status)"

{
  echo "# This file is auto-generated by \`scripts/update_rust_submodules.sh\`."
  echo "# Do not edit manually."
  echo "#"
  echo "# Why this exists:"
  echo "# - Git submodule contents are NOT included in crates.io packages."
  echo "# - When building from crates.io, \`rust/build.rs\` uses these pins to fetch missing"
  echo "#   submodules into a cache directory."
  echo "#"
  echo "# To update:"
  echo "#   bash scripts/update_rust_submodules.sh"
  echo
} > "${tmp}"

# Iterate submodule entries from .gitmodules via git-config for robustness.
# Output keys look like: "submodule.3rdparty/dlpack.path 3rdparty/dlpack"
while read -r key path; do
  [[ -z "${key}" || -z "${path}" ]] && continue

  name="${key#submodule.}"
  name="${name%.path}"
  url="$(git config -f .gitmodules --get "submodule.${name}.url")"
  sha="$(printf '%s\n' "${sub_status}" | awk -v p="${path}" '
    $2 == p {
      sha = $1
      sub(/^[\\-\\+U]/, "", sha)
      print sha
      exit
    }
  ')"

  if [[ -z "${url}" ]]; then
    echo "error: missing url for submodule '${name}' in .gitmodules" >&2
    exit 1
  fi
  if [[ -z "${sha}" ]]; then
    echo "error: missing pinned sha for submodule path '${path}'" >&2
    echo "hint: run: git submodule update --init --recursive" >&2
    exit 1
  fi

  section="$(basename "${path}")"

  {
    echo "[submodules.${section}]"
    echo "path = \"${path}\""
    echo "url = \"${url}\""
    echo "rev = \"${sha}\""
    echo
  } >> "${tmp}"
done < <(git config -f .gitmodules --get-regexp '^submodule\..*\.path$' | sort)

mkdir -p "$(dirname "${out}")"
mv "${tmp}" "${out}"
trap - EXIT

echo "Wrote ${out}" >&2


