on:
  workflow_dispatch:

jobs:
  run_tmate_session:
    name: Run tmate session on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-14, macos-13]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        exclude:
          - os: macos-13
            python: '3.13'
            # The reason for the exclusion is that pytorch distribution
            # can't be found by pip on macos-13 with python 3.13.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
        with:
          limit-access-to-actor: true
